<?php

function mail_form_block_info() {
  $blocks['mail_form'] = array(
    // The name that will appear in the block list.
    'info' => t('Mail Form'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

function mail_form_custom_form($form_state)
{
    $form = array();

    $form['name'] = array(
        '#type'         => 'textfield',
        '#title'        => t("Enter a mail"),
        '#weight'       => 10,
        '#required'     => true,
    );

    $form['submit'] = array(
        '#type'         => 'submit',
        '#value'        => t("Submit"),
        '#weight'       => 20,
    );

    return $form;
}

/**
 * Implementation of hook_block_view().
 */
function mail_form_block_view($delta = "")
{
    $block = array();

    switch($delta)
    {
        case "mail_form":
            $block['subject'] = t("");
            $block['content'] = drupal_get_form("mail_form_custom_form");
            break;
    }

    return $block;
}

function mail_form_custom_form_validate($form, &$form_state){
  $mail = $form_state['values']['name'];
  if (!filter_var($mail ,FILTER_VALIDATE_EMAIL)){
    form_set_error('name', t('You must enter valid email.'));
  }
}

function mail_form_custom_form_submit($form, &$form_state){
  $mail = $form_state['values']['name'];
  $insert = db_insert('mail_form_list')
		-> fields(array(
			'mail' => $mail,
			'date' => date('U'),
		))
		->execute();
	
	drupal_set_message(t('Email have been saved'));
}






/**
 * Implements hook_menu().
 */
function mail_form_menu() {
  $items = array();

  $items['admin/config/content/mail_form'] = array(
    'title' => 'Mail Form',
    'description' => 'Configuration for Mail Form module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mail_form_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: Current posts settings
 *
 * @see current_posts_menu()
 */
function mail_form_form($form, &$form_state) {
  $form['mail_form_separator'] = array(
    '#type' => 'textfield',
    '#title' => t('Separator'),
    '#default_value' => variable_get('mail_form_separator', ';'),
    '#size' => 1,
    '#maxlength' => 1,
    '#description' => t('The separator for export.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements validation from the Form API.
 * 
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state 
 *   during processing.
 */
function mail_form_form_validate($form, &$form_state){
  $separator = $form_state['values']['mail_form_separator'];
  if ($separator != ';' && $separator != ','){
    form_set_error('mail_form_separator', t('You must enter , or ;.'));
  }
}



